name: Docker Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  Init:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      compose_environment: ${{ steps.setvars.outputs.compose_environment }}
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "compose_environment=main" >> $GITHUB_OUTPUT
          fi
          if [[ "${{github.base_ref}}" == "production" || "${{github.ref}}" == "refs/heads/develop" ]]; then
            echo "compose_environment=develop" >> $GITHUB_OUTPUT
          fi
  BuildAndPushImage:
    name: Build and push image
    runs-on: self-hosted
    env:
      REGISTRY: docker.io
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      IMAGE_NAME: uninspiredstudioops/highlights-api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Log into registry
        uses: docker/login-action@v3 # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "infra/Dockerfile"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          platforms: [linux/amd64, linux/arm64]
          cache-from: type=gha
          cache-to: type=gha,mode=max
